# Generated by Django 4.0.6 on 2022-08-23 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_slug', models.SlugField(max_length=264, unique=True)),
                ('cat_description', models.CharField(max_length=160)),
                ('cat_image', models.URLField()),
                ('cat_image_up', models.ImageField(blank=True, upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=264)),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('blog_description', models.CharField(max_length=160)),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(blank=True, upload_to='blog_images')),
                ('image_url', models.URLField(max_length=160)),
                ('blog_tags', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_category', to='blogApp.blogcategory')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
