# Generated by Django 4.0.6 on 2022-08-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='contact_mail',
        ),
    ]
