# Generated by Django 4.0.6 on 2022-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_rename_email_contact_contact_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_mail', models.EmailField(max_length=100)),
            ],
        ),
    ]
